DROP TABLE IF EXISTS reviews;

CREATE TABLE reviews(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	course TEXT NOT NULL,
	Term TEXT NOT NULL,
	Instructor TEXT NOT NULL,
	Rating INTEGER,
	Review TEXT NOT NULL

);
